### ISSUE TITLE
Замечания

### ISSUE THREAD

**Issue by maximpetrov** [Danil891/second_task_vol.2#1]
1. Не стоит оставлять `IOException` без обработки в `main`.
1. https://github.com/Danil891/second_task_vol.2/blob/f08d1281241ae3b5a1fb8e24974927ad56536e6c/src/Uniq.java#L39 Эту переменную можно объявить внутри цикла.
1. `checkString` хранит предыдущую строку. Лучше сделать так, чтобы не нужно было по второму разу приводить её в нижний регистр и отрезать начало.
1. https://github.com/Danil891/second_task_vol.2/blob/f08d1281241ae3b5a1fb8e24974927ad56536e6c/src/Uniq.java#L59 Лучше не создавать лишний `BufferedWriter`, а поместить это создание в `else`.
1. https://github.com/Danil891/second_task_vol.2/blob/f08d1281241ae3b5a1fb8e24974927ad56536e6c/src/Uniq.java#L69 Вместо `String.valueOf()` используйте `toString()`.
1. Не совсем логично, что Ваш метод и печатает в консоль/файл, и возвращает результирующий список. Список действительно может понадобиться, но для того, чтобы его получить, нужно куда-то "намусорить". Так что либо не возвращайте список, либо сделайте два метода.
1. https://github.com/Danil891/second_task_vol.2/blob/f08d1281241ae3b5a1fb8e24974927ad56536e6c/test/tests.java#L30 Сравнивать результаты `toString` некорректно. Сделайте нормальный `equals` у `Pair`, чтобы можно было честно сравнить списки.
1. Должны быть тесты, проверяющие полную работу, то есть результат в файле, а не возвращённый список. У Вас даже есть тест с указанным выходным файлом, но он ничем не отличается от аналогичного с выводом в консоль, потому что Вы там тоже проверяете возвращённый список, а не читаете файл.

**Comment by Danil891** [comment]
Пофиксил недочеты
И добавил тесты с проверкой файлов

**Comment by maximpetrov** [comment]
1. Пункт 1 не исправлен.
1. Пункт 3 исправили наполовину: не храните обрезанную строку
1. https://github.com/Danil891/second_task_vol.2/blob/321e9930cb9df3ec12d96c66ae74c6ddc422e073/src/Uniq.java#L15 Зачем эта локальная переменная сделана полем класса?
1. https://github.com/Danil891/second_task_vol.2/blob/321e9930cb9df3ec12d96c66ae74c6ddc422e073/src/Uniq.java#L48-L50 Зачем этот частный случай, почему просто не сделать это при инициализации первой строкой?
1. https://github.com/Danil891/second_task_vol.2/blob/321e9930cb9df3ec12d96c66ae74c6ddc422e073/src/Uniq.java#L75  Лучше `newLine()`.
1. По пункту 6. Вы не исправили "некрасивость", всё равно, чтобы получить список, нужно вызвать метод который куда-то что-то пишет. Лучше сделать метод, который возвращает список, и метод, который печатает в файл список, который получает из первого метода.

**Comment by Danil891** [comment]
А обработку чего конкретно надо сделать в main, я не совсем понимаю какая ошибка там может быть.
По поводу 3го пункта, я её перестал хранить, я обрезаю только в условии, а так она либо в нижнем регистре, либо остается без изменений.
Все остальное, как понял, исправил.

**Comment by maximpetrov** [comment]
1. У Вас `throws IOException` в `main` из-за того, что могут возникнуть такого рода исключения при открытии файлов. Вот эту ситуацию и нужно обработать.
1. Пункт 2 Вы, видимо, не поняли. То, что Вы исправили пункт 3 и сделали переменную локальной, это хорошо. Но ещё неплохо было бы обрезать строку как раз не в условии, а перед ним, чтобы сохранить в переменную. Тогда не придётся не только в нижний регистр два раза переводить, но и обрезать.
1. Пункт 6 по сути всё ещё не исправлен. Зачем Вы вызываете `printer()` из `runUniq()`?

**Comment by Danil891** [comment]
Обработал ситуацию, когда неправильно введен файл.
По пункту 6, я после проверки забыл убрать его от туда.
Пункт 2 исправил.

**Comment by maximpetrov** [comment]
У Вас не хватает теста, который проверяет ситуацию, когда есть игнорирование начальных символов и игнорирование регистра.

**Comment by Danil891** [comment]
Сделал.

**Comment by maximpetrov** [comment]
Этот тест не показательный, Вы символы с отличающимся регистром находятся в отбрасываемой части

**Comment by Danil891** [comment]
Понял, изменил тест для смежного варианта, чтобы разный регистр был в отбрасываемой части и в обрабатываемой

**Comment by maximpetrov** [comment]
На самом деле, я ошибся. Такой тест тоже нужен, но на самом деле я хотел ещё тест для той же комбинации флагов, но в котором отбрасываемое начало отличается не только регистром.

**Comment by Danil891** [comment]
Хорошо, сейчас добавлю.

**Comment by Danil891** [comment]
Сделал, все работает

**Comment by maximpetrov** [comment]
Лень уже намекать через тестовые случаи, но у Вас аналогичная ошибка при обработке первой строки.

**Comment by Danil891** [comment]
Понял

**Comment by maximpetrov** [comment]
Если Вы считаете, что исправили, то это не так. От перестановки вызовов ничего не поменяется, проблема в том, чтобы Вы не обрезаете строку, если нет `ignoreRegister`
